- lldb/source/Core/Module.cpp
This PR makes a minor change to check for object offset matching in ModuleSpec matching. 
Since AMD code object is embedded into host CPU object file, GPU module will have non-zero offset. This is required to support parsing AMD GPU module out of host ELF module.
> Check object offset in ModuleSpec matching

- lldb/source/Plugins/Process/gdb-remote/LLDBServerPlugin.cpp
- lldb/source/Plugins/Process/gdb-remote/LLDBServerPlugin.h
- lldb/tools/lldb-server/CMakeLists.txt
- lldb/tools/lldb-server/Plugins/AMDGPU/CMakeLists.txt
- lldb/tools/lldb-server/Plugins/AMDGPU/LLDBServerPluginAMDGPU.cpp
- lldb/tools/lldb-server/Plugins/AMDGPU/LLDBServerPluginAMDGPU.h
- lldb/tools/lldb-server/Plugins/AMDGPU/ProcessAMDGPU.cpp
- lldb/tools/lldb-server/Plugins/AMDGPU/ProcessAMDGPU.h
- lldb/tools/lldb-server/Plugins/AMDGPU/RegisterContextAMDGPU.cpp
- lldb/tools/lldb-server/Plugins/AMDGPU/RegisterContextAMDGPU.h
- lldb/tools/lldb-server/Plugins/AMDGPU/ThreadAMDGPU.cpp
- lldb/tools/lldb-server/Plugins/AMDGPU/ThreadAMDGPU.h
- lldb/tools/lldb-server/Plugins/CMakeLists.txt
- lldb/tools/lldb-server/Plugins/MockGPU/LLDBServerPluginMockGPU.cpp
- lldb/tools/lldb-server/Plugins/MockGPU/LLDBServerPluginMockGPU.h
- lldb/tools/lldb-server/lldb-gdbserver.cpp
- llvm/cmake/modules/CrossCompile.cmake
This is initial implementation for AMD GPU plugin based on @clayborg's GPU plugin model.
* By default, if `ROCM_PATH` is not defined, it will link `MockGPUPlugin`.
* When cmake was configured with `-DROCM_PATH:PATH=<path_to_rocm_path>`, it will link `AMDGPUPlugin`
* `AMDGPUPlugin` will search under `${ROCM_PATH}/lib/cmake/amd-dbgapi` to link AMD's debug API. 
* When `ROCM_PATH` is defined, lldb-gdbserver will automatically create&install `LLDBServerPluginAMDGPU` instead of `LLDBServerPluginMockGPU`. 
* Changes in `llvm/cmake/modules/CrossCompile.cmake` is required to support passing `-DROCM_PATH` down, when `-DLLVM_OPTIMIZED_TABLEGEN:BOOL=TRUE` is enabled. 
**This implementation meets two key requirements of AMD GPU debugging**
* All ptrace() calls have to happen in the same thread
* AMD …
> AMD GPU plugin v1

- lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.h
- lldb/tools/lldb-server/CMakeLists.txt
- lldb/tools/lldb-server/Plugins/AMDGPU/LLDBServerPluginAMDGPU.cpp
- lldb/tools/lldb-server/Plugins/CMakeLists.txt
- lldb/tools/lldb-server/Plugins/MockGPU/LLDBServerPluginMockGPU.cpp
These started showing up after the rebase to llvm main branch. An upstream [change](https://github.com/llvm/llvm-project/commit/cf9546b826619890e965367a3e4d0da1991ba929) removed the ConnectionFileDescriptor constructor that takes a raw pointer.
> Fix compile errors

- lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp
Currently we are discarding these errors, instead we should report them. This is how I discovered that many of the GPUActions were not being processed because sometimes I had the GPU process running instead of stopped.
> [LLDB][GPU] Handle GPUAction errors

- lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp
As preliminary context, everything belows applies to the client. The server side is all fine.
For NVIDIA, after connecting to the GPU process we issue a resume_gpu GPUAction. We were doing that after connecting to the process asynchronously, which resulted in a race condition in which the following actions were happening at the same time:
- the gpu process was handling its stop state, fetching the state of its threads
- the GPUAction was issuing a Resume request
this caused that very often, after resuming, the gpu process was left in a Running state but with the thread metadata not cleared. Then, in the next stop event, it would reuse the previous thread metadata instead of using the new one.
Not only that, this sometimes caused many event listeners that were processing the original stop …
> [LLDB][GPU] Connect synchronously to the gpu process

- lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp
I'm adding comments reflecting the conversation we had last week on race conditions and assumptions when executing HandleGPUActions.
> [LLDB][GPU] Add a comment warning the assumptions in HandleGPUActons

- lldb/tools/lldb-server/Plugins/AMDGPU/LLDBServerPluginAMDGPU.cpp
We accidentally left in the mock gpu breakpoint in LLDBServerPluginAMDGPU when copying the sources as an example.
> [amd] Remove mock gpu example breakpoint

- lldb/docs/use/gpu-support.rst
- lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationServerLLGS.h
- lldb/tools/lldb-server/CMakeLists.txt
- lldb/tools/lldb-server/Plugins/AMDGPU/CMakeLists.txt
- lldb/tools/lldb-server/Plugins/CMakeLists.txt
- lldb/tools/lldb-server/lldb-gdbserver.cpp
- Add LLDB_ENABLE_[GPU plugin]_PLUGIN variables to programmatically enable each GPU plugin
- Make all the activation logic for all those plugins independent. This results in no `else` conditions, which makes rebases simpler.
- Theoretically, this would allow multiple plugins to be running at the same time. This sounds nice even though I don't think we'll ever work on it.
- Scaffold a tiny documentation file where we can put all the information related to the GPU plugins.
> [LLDB][GPU] Decouple plugins and scaffold documentation

- lldb/packages/Python/lldbsuite/test/builders/builder.py
- lldb/packages/Python/lldbsuite/test/configuration.py
- lldb/packages/Python/lldbsuite/test/dotest.py
- lldb/packages/Python/lldbsuite/test/dotest_args.py
- lldb/packages/Python/lldbsuite/test/make/Makefile.rules
- lldb/test/API/gpu/amd/basic/Makefile
- lldb/test/API/gpu/amd/basic/TestBasicAmdGpuPlugin.py
- lldb/test/API/gpu/amd/basic/hello_world.hip
- lldb/test/API/gpu/amd/lit.local.cfg
- lldb/test/API/lit.cfg.py
- lldb/test/API/lit.site.cfg.py.in
This commit adds some basic unit tests for the AMDGPU plugin.
It modifies the test configuration to expose the HIPCC compiler
to the make file when the AMDGPU plugin is enabled. It also modifies
the dotest framework so that we can compile .hip files using the
Makefile.rules like we do for other tests.
The unit tests compile a simple hip program and validate that we do
create the gpu target succesfully and that we can hit a breakpoint
in the gpu code.
> Add tests for amdgpu lldb-server plugin

- lldb/tools/lldb-server/CMakeLists.txt
This removes a check that ensures that at most one plugin was enabled for a build configuration.
With this change, multiple plugins can be enabled in the build, which allows for running all nvidia and amd tests, for example.
> [LLDB][GPU] Allow for multiple plugins in the same build

- lldb/include/lldb/Utility/GPUGDBRemotePackets.h
- lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp
- lldb/tools/lldb-server/Plugins/AMDGPU/LLDBServerPluginAMDGPU.cpp
I'm experimenting with initializating asynchronously and I think it's a good idea to make sync initialization an option in the GPU Actions. Given that AMD was using this by default, I modified it accordingly.
> [LLDB][GPU] Add a GPUActions option for sync initialization

- lldb/test/API/gpu/amd/basic/TestBasicAmdGpuPlugin.py
- lldb/tools/lldb-server/Plugins/AMDGPU/LLDBServerPluginAMDGPU.cpp
Currently we set the gpu loader breakpoint by address in the `amd_dbgapi_insert_breakpoint_callback` callback. This means we need to halt the CPU in order to correctly set the breakpoint. When we halt the CPU it shows up as a public stop to the user and interrupts the debugging flow.
This PR changes it so that we set the loader breakpoint by name when we first create the gpu connection. We set the breakpoint on the `rocr::_loader_debug_state` function which was discovered by looking up the address passed into the callback.
This is a bit of a hack since the function name could potentially change over time or may be unavailable if the runtime was statically linked. But we use it for now to make the debugger experience better until we can find a more permanant solution.
> [amd] Set gpu loader breakpoint by name

- lldb/source/Utility/GPUGDBRemotePackets.cpp
We rely on this value to determine whether to connect to the gpu process synchronously or not. It was not being serialized in the json which is a problem for the amdgpu plugin since we currently require it to be set to true.
> [LLDB][GPU] Convert GPUPluginConnectionInfo synchronous member to/from json

- lldb/packages/Python/lldbsuite/test/tools/gpu/amdgpu_testcase.py
- lldb/packages/Python/lldbsuite/test/tools/gpu/gpu_testcase.py
- lldb/test/API/gpu/amd/basic/TestBasicAmdGpuPlugin.py
This generalizes https://github.com/clayborg/llvm-project/pull/22 by creating a base test class for all GPU tests.
I changed some getters to properties to match the patterns already used by LLDB tests.
> [NFC] Create a base class for all GPU tests

- lldb/tools/lldb-server/Plugins/AMDGPU/LLDBServerPluginAMDGPU.cpp
Update log to use the int format instead of string.
> Fix build for breakpoint id change from string to int

- lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp
- lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.h
We are currently missing a call to notify threads waiting on the StateSync condition variable when resuming the process. This causes the native process to miss out on notifications that the gpu process has resumed when waiting for the gpu to process to hit its requested stop id when `wait_for_gpu_process_to_resume` is true in GPUActions.
> Call notify on StateSync condition variable when resuming

- lldb/include/lldb/Target/ABI.h
- lldb/include/lldb/Target/Process.h
- lldb/source/Target/Process.cpp
- lldb/source/Target/RegisterContext.cpp
- Added a method to ABI for retrieving the default address space for saved registers when unwinding, returning an optional integer address space identifier.
- Updated Process to allow a numeric address space ID when resolving addresses for memory reads.
- Enhanced RegisterContext to check for ABI-specified address spaces when reading register values from memory.
> [LLDB][NVIDIA] Enhance ABI and Process for Address Space Management

- lldb/include/lldb/Utility/GPUGDBRemotePackets.h
- lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp
- lldb/source/Utility/GPUGDBRemotePackets.cpp
- lldb/test/API/gpu/mock/basic/TestBasicMockGpuPlugin.py
- lldb/tools/lldb-server/Plugins/MockGPU/LLDBServerPluginMockGPU.cpp
- Add an option to GPUPluginConnectionInfo that indicates LLDB to copy the cpu breakpoints to the gpu target during connection time.
- After connection, breakpoints can be set independently on each target.
If this gets greenlit, I'll write corresponding support to the mock gpu and add some tests.
> [LLDB][GPU] Add support for copying cpu breakpoints during connection

- lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp
- lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.h
- lldb/tools/lldb-server/Plugins/AMDGPU/LLDBServerPluginAMDGPU.cpp
There is a bug that happens when you connect to the server where target list shows:
```
(lldb) target list
Current targets:
target #0: /data/users/peix/llvm/gpu/build/Debug/a.out ( arch=x86_64-unknown-linux-gnu, platform=host, pid=622763, state=stopped )
target #1: <none> ( arch=amdgcn-amd-amdhsa--gfx942, platform=host, pid=1, state=stopped )
* target #2: <none> ( platform=host, state=unloaded )
```
The workflow: 
Process Launch -> initial stop (lldb always stops at launch) -> server gets notified -> 
server decide to send GPU actions in NativeProcessIsStopping() -> ready is returning true in ReadyToSendConnectionRequest -> 
Client is receiving the stop packet (our first process, GPU target created) ->  m_last_stop_packet = response (contains GPUactions) ->
LLDB calls …
> [lldb][GPU] Fix bug where we handle GPUActions multiple times

- lldb/tools/lldb-server/Plugins/AMDGPU/AmdDbgApiHelpers.h
- lldb/tools/lldb-server/Plugins/AMDGPU/LLDBServerPluginAMDGPU.cpp
- lldb/tools/lldb-server/Plugins/AMDGPU/LLDBServerPluginAMDGPU.h
- lldb/tools/lldb-server/Plugins/AMDGPU/ProcessAMDGPU.cpp
Create a unique_ptr type that can be used to automatically free memory
allocated by the amddbg api. It calls back into the
LLDBServerPluginAMDGPU::FreeDbgApiClientMemory function to actually free
the memory.
Opportunistically use this new wrapper to fix a memory leak.
> [GPU][AMD] Create unique_ptr to deallocate client memory
